/**:
    ros__parameters:
      #video_device: "/dev/v4l/by-id/usb-046d_Logitech_BRIO_E427DB1F-video-index0"
      video_device: "/dev/v4l/by-id/usb-046d_Logitech_BRIO_2F8BAD49-video-index0"
      framerate: 10.0
      io_method: "mmap"
      frame_id: "left_wrist_cam_link"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 3840 
      image_height: 2160 
      camera_name: "left_wrist_cam"
      # reusing same camera intrinsics only for demo, should really be unique for camera2"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: 40